### ISSUE TITLE
Does it have deploy.prototxt

### ISSUE THREAD

**Issue by ray0809** [Engineering-Course/LIP_SSL#11]
Would you please release the deploy.prototxts for testing only one picture

**Comment by xmba15** [comment]
@ray0809 in case you still need the deploy.prototxt
https://github.com/bajsk/LIP_SSL/blob/master/human/config/attention/deploy.prototxt

**Comment by ghost** [comment]
How can I test only a single image directly without using test.txt or val.txt?

**Comment by Engineering-Course** [comment]
Sorry, but we haven't prepared a demo for testing a single image yet.
