### ISSUE TITLE
different crop_size in TRAIN and TEST phase?

### ISSUE THREAD

**Issue by s5248** [Engineering-Course/LIP_SSL#12]
I observed that in the $root_dir/LIP_SSL/human/config/attention, the crop_sizes in train.prototxt and test.prototxt are not the same, training use crop_size=321,while testing use crop_size=640, It's true and why this is resonable? Is the accracy performances in the paper were reached by this setting? Thanks for your response.

**Comment by Engineering-Course** [comment]
The training uses cropped patches while testing uses full images.
