### ISSUE TITLE
error Class_id

### ISSUE THREAD

**Issue by vitiennam** [Engineering-Course/LIP_SSL#13]
Hi author,

Thanks for your projects, I have problem with your LIPS dataset (image + mask):
As you can see I show this image (LIP/TrainVal_images/TrainVal_images/train_images/124117_202251.jpg):
class_id = [ 2  5 13 14 15]
![image](https://user-images.githubusercontent.com/20283416/35043684-1a4570bc-fbc0-11e7-8561-171ffcdf162d.png)

LIP/TrainVal_images/TrainVal_images/train_images/124122_1735422.jpg:
class_id = [ 2  5  8  9 13 17]
![image](https://user-images.githubusercontent.com/20283416/35043787-7b7746b2-fbc0-11e7-97be-9a9194053e70.png)

LIP/TrainVal_images/TrainVal_images/train_images/12413_1224729.jpg
class_id = [ 1  2  7  9 14 18 19]
![image](https://user-images.githubusercontent.com/20283416/35043839-b25d7dfe-fbc0-11e7-9e16-64d4353bd3dd.png)

I have follow your id class but maybe it is not right:
1.Hat
2.Hair
3.Sunglasses
4.Upper-clothes
5.Dress
6.Coat
7.Socks
8.Pants
9.Glove
10.Scarf
11.Skirt
12.Jumpsuits
13.Face
14.Right-arm
15.Left-arm
16.Right-leg
17.Left-leg
18.Right-shoe
19.Left-shoe

Please help me

Thanks
Nam

**Comment by Engineering-Course** [comment]
Maybe you can find the id class on our [dataset](http://www.sysu-hcp.net/lip/parsingchallenge.php) website.
And we have updated the id class for download.

**Comment by vitiennam** [comment]
Thanks for your support

**Comment by vitiennam** [comment]
One more thing,

With multi dataset, It have Multi_TrainVal_parsing_annotation but it do not have Multi_Test_parsing_annotation.

Thanks

**Comment by Engineering-Course** [comment]
Test annotations are withheld for benchmarking purpose.
You can submit your results for evaluation on our benchmark website.
