### ISSUE TITLE
questions for training

### ISSUE THREAD

**Issue by XianWu18** [Engineering-Course/LIP_SSL#14]
Hi, I have some questions for training. It seems like run_human.sh contains only one training step, but your paper says there are two training steps. The batch size in train.prototxt is 1 but that is 10 in your paper, which one is correct? 

And I have downloaded the attention models from the deeplab website. There are init.caffemodel and train2_iter_8000.caffemodel in the zip file. Which one should be used as the init.caffemodel for training?

I'm looking forward to your reply.

**Comment by Engineering-Course** [comment]
We found that the batch size does not affect the performance. You can modify it according to your GPU memory.
We use init.caffemodel for training.

**Comment by XianWu18** [comment]
I got it. Thank you very much!
