### ISSUE TITLE
error

### ISSUE THREAD

**Issue by YOKE** [Engineering-Course/LIP_SSL#15]
In the process of training, I met this error:
F0307 17:08:57.373412 27727 data_transformer.cpp:475] Check failed: img_height == seg_height (409 vs. 0) 

I don't know how to solve it, could you please give me some suggestions? Thank you very much!

**Comment by Engineering-Course** [comment]
It seems that the image and the segmentation gt are inconsistent. 
Please check your image list and the directory.

**Comment by YOKE** [comment]
Could you give me the train, val, test lists in ssl/humIan/list? Each type contains a list for path and a list for id (e.g., train.txt and train_id.txt). I can't figure it out.

**Comment by Engineering-Course** [comment]
Following is an example of train.txt:
        /images/1000_1234574.jpg /labels/1000_1234574.png
And there are only image ids in train_id.txt like:
        1000_1234574
