### ISSUE TITLE
models trained on ATR dataset

### ISSUE THREAD

**Issue by Vicky0522** [Engineering-Course/LIP_SSL#16]
Are there any pre-trained models trained on ATR dataset?
Network presented here is only suitable for LIP dataset, since ATR has 18 categories but not 20 categories of LIP.
Thank you very much!

**Comment by Engineering-Course** [comment]
Sorry that we have not prepared the models trained on ATR yet.
But after a minor modification of joints configurations, the network can be trained on ATR or other human parsing datasets.
