### ISSUE TITLE
Incorrect output in test

### ISSUE THREAD

**Issue by mzemlyanikin** [Engineering-Course/LIP_SSL#19]
Hi!

I'm trying to use your code to get segmentations.
In my input images there is usually one rather large person.
But output segmentation mask is always filled with fives.

Can you tell me what I'm doing wrong?

**Comment by Engineering-Course** [comment]
Could you please give some examples?

**Comment by codaibk** [comment]
I also get same problem. all of values in mat file = 5 therefore the output result segmentated image just one color.
![capture](https://user-images.githubusercontent.com/28720676/37892088-3112a066-3109-11e8-9514-ee32435ec071.PNG)
![9](https://user-images.githubusercontent.com/28720676/37892117-476922a4-3109-11e8-9fa1-44058b59e536.png)

**Comment by Engineering-Course** [comment]
Does the input image come from LIP?
What's the size of the input image?

**Comment by codaibk** [comment]
I used the LIP models but the input for testing from another source. My input images size is 150 x 205

**Comment by Engineering-Course** [comment]
I have not seen this problem and the code and model work well even testing on the image from other sources on my device. So I'm not sure what makes the difference.
Maybe you can check whether the trained caffemodel is downloaded correctly.

**Comment by codaibk** [comment]
Im sure that i downloaded corect your model from website "https://drive.google.com/uc?id=0BzvH3bSnp3E9eHMyVS1RbUVDems&export=download". But i dont why the output mat file contains same value.
Im using val for testing and this is my "Val.txt" list file
![image](https://user-images.githubusercontent.com/28720676/37898829-6db184a2-311c-11e8-97dc-2a0d1812dbeb.png)

**Comment by codaibk** [comment]
I think maybe my problem is related to class id. I dont know where i put the class_id file and i also didnt see it in your project. Could you tell me where should i put it in project?
![image](https://user-images.githubusercontent.com/28720676/37916692-12f69d94-314f-11e8-8d42-aadf9381bf6f.png)

**Comment by Engineering-Course** [comment]
But there is no need for the class_id file when testing.

**Comment by codaibk** [comment]
so how about this sentence? "Set up your init.caffemodel before training and test.caffemodel before testing. You can simply use a soft link.". test.caffemodel is "LIP models" in my case? because i just download your "LIP model" then put it in "human/model/attention" folder and run testing for it. 
Thank

**Comment by Engineering-Course** [comment]
Rename the model, 

> attention+ssl.caffemodel

 that you downloaded as 

> test.caffemodel

**Comment by Anguliachao** [comment]
> Im sure that i downloaded corect your model from website "https://drive.google.com/uc?id=0BzvH3bSnp3E9eHMyVS1RbUVDems&export=download". But i dont why the output mat file contains same value.
> Im using val for testing and this is my "Val.txt" list file
> ![image](https://user-images.githubusercontent.com/28720676/37898829-6db184a2-311c-11e8-97dc-2a0d1812dbeb.png)

Hi @codaibk  , May I ask how do you manage to test with the shell script successfully, I made the exactly same val.txt , but error prompts
`data_transformer.cpp:474] Check failed: img_channels == data_channels (1 vs. 3)`
