### ISSUE TITLE
out of memory issue using GTX1080

### ISSUE THREAD

**Issue by staywithme23** [Engineering-Course/LIP_SSL#2]
I0524 00:14:45.317162 21868 net.cpp:816] Ignoring source layer accuracy_first_res1
I0524 00:14:45.317179 21868 net.cpp:816] Ignoring source layer loss_first_res075
I0524 00:14:45.317183 21868 net.cpp:816] Ignoring source layer accuracy_first_res075
I0524 00:14:45.317186 21868 net.cpp:816] Ignoring source layer label_shrink16
I0524 00:14:45.317189 21868 net.cpp:816] Ignoring source layer label_shrink16_label_shrink16_0_split
I0524 00:14:45.317193 21868 net.cpp:816] Ignoring source layer loss_first_res05
I0524 00:14:45.317195 21868 net.cpp:816] Ignoring source layer accuracy_first_res05
I0524 00:14:45.319630 21868 caffe.cpp:252] Running for 9999 iterations.
F0524 00:14:45.558805 21868 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f0562f8cdaa  (unknown)
    @     0x7f0562f8cce4  (unknown)
    @     0x7f0562f8c6e6  (unknown)
    @     0x7f0562f8f687  (unknown)
    @     0x7f056379ae91  caffe::SyncedMemory::to_gpu()
    @     0x7f056379a1f9  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f0563784822  caffe::Blob<>::mutable_gpu_data()
    @     0x7f05636ebe88  caffe::BaseConvolutionLayer<>::forward_gpu_gemm()
    @     0x7f05637aa9b6  caffe::ConvolutionLayer<>::Forward_gpu()
    @     0x7f0563726831  caffe::Net<>::ForwardFromTo()
    @     0x7f0563726ba7  caffe::Net<>::ForwardPrefilled()
    @           0x406d74  test()
    @           0x4059dc  main
    @     0x7f0562297f45  (unknown)
    @           0x406111  (unknown)
    @              (nil)  (unknown)
run_human.sh: line 82: 21868 Aborted                 (core dumped) ${CMD}
======================================
Hi, I'm using GTX1080, it seems like I face cuda memory issue if all my setting is good.
Have you tried on GTX 1080 and is it possible that I make batch size smaller?

**Comment by staywithme23** [comment]
Should I uncomment USE_CUDNN := 1?

1. I ran `make all -j4` in the code folder

2. Set test=1, train=0 in the run file just for testing, then ran into this error 

Thanks in advance!

**Comment by staywithme23** [comment]
This is my Cmake result:
- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_61
--   cuDNN             :   Yes (ver. 5.1.10)

**Comment by Engineering-Course** [comment]
Yes, you should use cuDNN, otherwise 8G memory GPU is not enough for the network.

**Comment by staywithme23** [comment]
@Engineering-Course Yes, using cuDNN is the perfect solution!
Thank you

**Comment by bhalajin** [comment]
@Engineering-Course What is the minimum GPU requirements (with cuDNN and without cuDNN) for testing the network?

**Comment by Engineering-Course** [comment]
It depends on the input size.
8G GPU memory is enough for a 513*513 input image for testing.
