### ISSUE TITLE
Error in testing with pretrained model

### ISSUE THREAD

**Issue by bhalajin** [Engineering-Course/LIP_SSL#22]
I am trying to test with the pre-trained model available in the readme.

Downloaded the LIP dataset and placed the images, segmentations and list as specified
Downloaded the caffemodel and renamed it as test.caffemodel

I have existing caffe in my machine (windows 7 64 bit) and using the same for testing. Changed the path in run_human.sh
Getting the following error when running the run_human.sh

```
Testing net human/attention
Running D://Projects//caffe//tools//Release//caffe.exe test --model=human/config/attention/test_val.prototxt --weights=human/model/attention/test.caffemodel --gpu=0 --iterations=1
I0404 20:37:13.862496  9404 caffe.cpp:276] Use GPU with device ID 0
I0404 20:37:13.940496  9404 caffe.cpp:280] GPU device name: GeForce GT 720
I0404 20:37:14.190094  9404 common.cpp:36] System entropy source not available, using fallback algorithm to generate seed instead.
[libprotobuf ERROR C:\Users\guillaume\work\caffe-builder\build_v120_x64\packages\protobuf\protobuf_download-prefix\src\protobuf_download\src\google\protobuf\text_format.cc:298] Error parsing text-format caffe.NetParameter: 14:15: Message type "caffe.ImageDataParameter" has no field named "label_type".
*** Check failure stack trace: ***
```

**Comment by Engineering-Course** [comment]
The codes are for the Linux OS. The compatibility on Windows OS is not tested.

**Comment by rshivansh** [comment]
@Engineering-Course Can you tell me how to run the pretrained model on linux.
Im unable to do so

**Comment by Engineering-Course** [comment]
Try to follow README to run. 
What's your confusion?

**Comment by rshivansh** [comment]
@Engineering-Course I was able to figure out the issue. Thanks!
Could you pls let me know whats the difference between LIP-SSL and LIP-JPPNET. Is it only the multi-person parsing extra in jppnet? or something else also.
Thanks

**Comment by Engineering-Course** [comment]
You can refer to JPPNet paper which has detailed illustration of the difference between the two networks.

**Comment by aunmesh** [comment]
@rshivansh Please also describe what was the issue and solution. It is helpful for other people
