### ISSUE TITLE
代码测试问题

### ISSUE THREAD

**Issue by bugLoser** [Engineering-Course/LIP_SSL#23]
1.LIP数据集中的test_image部分没有test_id.txt只有val_id.txt，而且和trainVal中的val_id.txt一模一样，是否正常？
2.如果单单跑测试的话，是不仅仅需要test数据集么。我是把test压缩包中的文件放到human/data/images底下，并将val_id.txt放到相应的list底下，同时下载预训练好的模型改名成test.caffemodel放到相应model/attention文件夹下，不过跑run_human.sh的RUN_TEST的时候，提示缺少的是val.txt，所以我是根据文件路径生成了val.txt，这样的话跟第三点中的有冲突，并不是test.txt和test_id.txt。这样跑出来的话，跑出来结果loss为0。然后跑test_human.py的时候就提示需要val的图像。是我哪里理解错了么？

**Comment by Engineering-Course** [comment]
test_image里面的txt错了，现已更新。
跑测试的话 需要val数据集和val_id.txt
