### ISSUE TITLE
Is it impossible to train with new data for sketch-segmentation?

### ISSUE THREAD

**Issue by codaibk** [Engineering-Course/LIP_SSL#25]
Hi. I want to apply this model on sketch-segmentation. It means my input is sketch and my expected output is segmented image of sketch.  Is it impossible to apply this model on my new data? and what will i need to change in config to correct my training. So far my result was wrong.
Thanks

**Comment by Engineering-Course** [comment]
I think it also works for the sketch-segmentation task. But you should modify the setting of joint structure loss or uncomment it in the prototxts.

**Comment by codaibk** [comment]
Hi, Thank for reply.
Do you mean i need to uncomment "num_joint: 9" in prototxts file?
And how about "input_dim: 3", i need to change it to "input_dim: 1"? because my sketch input is gray-scale image
Thanks
Thanks,

**Comment by Engineering-Course** [comment]
Yes, the input_dim should be changed.
And I have updated prototxts for the network without structure loss.

**Comment by codaibk** [comment]
Hi, Thank a lot your your reply.
Could you also update the deploy.prototxts file without structure loss? we also need to use it for training?
Thanks

**Comment by Engineering-Course** [comment]
You can simply generate deploy.prototxt from the provided train.prototxt.
Thanks.

**Comment by codaibk** [comment]
Thank you ^^

**Comment by codaibk** [comment]
Hi, sorry for asking again. But i forgot to tell you that my sketch data is human's sketch, it will have same number class like your data. So should i still need to remove structure loss Like your suggestion?
Thanks

**Comment by Engineering-Course** [comment]
@codaibk  If so, you can use the structure loss.
