### ISSUE TITLE
what's type of the segmentation images in training data?

### ISSUE THREAD

**Issue by codaibk** [Engineering-Course/LIP_SSL#26]
Hi, The train segmentations data  is gray scale images or black and white image? I though the segmentations will have 20 colors corresponding to 20 labels. 
This is one of segmented image in your training data.
![77_471474](https://user-images.githubusercontent.com/28720676/39287331-cd9a8e6c-4955-11e8-8d3f-f58c0c2a10c8.png)
Thanks

**Comment by Engineering-Course** [comment]
It's a label map where the value of each pixel is from 0 to 19, corresponding to 20 labels. So it can't be visualized.

**Comment by codaibk** [comment]
whats the tool which you used to make label map for image? and did you change image to grayscale image after labeled map? because i saw that 3 channels in your image is same (R=G=B).
for my data, i used js-segment-annotator (http://kyamagu.github.io/js-segment-annotator/?view=edit&id=0) to annotator to label the image. but my result is color image (as bellow). so i'm thinking whether i should to change my image to grayscale image before run training
![1_a](https://user-images.githubusercontent.com/28720676/39293011-6277a9b6-496a-11e8-87a4-69f69241e4ba.png)

**Comment by Engineering-Course** [comment]
You should save it as a one-channel map with png format.

**Comment by codaibk** [comment]
Could you please tell me which tool you used for label map?
Thanks

**Comment by Engineering-Course** [comment]
Do you mean the annotation tool? We implement one by ourselves. And we have some post-process scripts to generate label maps. 
Acturally, you can transform any format to this kind of label map using Python or Matlab.

**Comment by codaibk** [comment]
Sorry, because im beginner in this field. Could you share your scripts to generate label maps ?
Thanks

**Comment by Engineering-Course** [comment]
Sorry. But I wrote the scripts only for our data and the code may not work for others.
