### ISSUE TITLE
"caffe.ImageDataParameter" has no field named "label_type"

### ISSUE THREAD

**Issue by andrewjong** [Engineering-Course/LIP_SSL#29]
Hello!
I get this error when trying to test the pretrained model. Could you help me figure it out please?

```
Testing net human/attention
Running /usr/bin/caffe.bin test              --model=human/config/attention/test_val.prototxt              --weights=human/model/attention/test.caffemodel              --iterations=10000
I1121 16:58:08.414149 24292 caffe.cpp:284] Use CPU.
[libprotobuf ERROR google/protobuf/text_format.cc:307] Error parsing text-format caffe.NetParameter: 14:15: Message type "caffe.ImageDataParameter" has no field named "label_type".
F1121 16:58:08.419540 24292 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: human/config/attention/test_val.prototxt
```

I believe the key part is this: `"caffe.ImageDataParameter" has no field named "label_type".`

This looks related to #22, but since that thread is closed with no posted solution, I'm opening a new issue.
Thank you for your time.

**Comment by Engineering-Course** [comment]
Do you use the caffe_ssl or the original caffe?
Please check that do you compile the customed caffe_ssl.

**Comment by andrewjong** [comment]
Oh I see, thank you!
Decided to switch to LIP_JPP instead because it's in TensorFlow (easier for me).

**Comment by ssjsusie** [comment]
> Do you use the caffe_ssl or the original caffe?
> Please check that do you compile the customed caffe_ssl.

Excuse me, Can you provide the CUDA version number for Caffe at compile time? Thank you!
