### ISSUE TITLE
"Check failed: matfp Error creating MAT file" during test process

### ISSUE THREAD

**Issue by lijiaqi** [Engineering-Course/LIP_SSL#6]
When I test the model, I got this errror when I run ```./run_human.sh```.

How should I deal with this problem?
```
...
...
F0912 10:56:18.593981  8397 matio_io.cpp:66] Check failed: matfp Error creating MAT file human/features/attentional/fc8_mask/labels/1270_1715217.png_blob_0.mat
*** Check failure stack trace: ***
    @     0x7fac995ea5cd  google::LogMessage::Fail()
    @     0x7fac995ec433  google::LogMessage::SendToLog()
    @     0x7fac995ea15b  google::LogMessage::Flush()
    @     0x7fac995ece1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fac99e17a7b  caffe::WriteBlobToMat<>()
    @     0x7fac99dc1092  caffe::MatWriteLayer<>::Forward_cpu()
    @     0x7fac99e46886  caffe::Net<>::ForwardFromTo()
    @     0x7fac99e46c47  caffe::Net<>::ForwardPrefilled()
    @           0x409115  test()
    @           0x4075c8  main
    @     0x7fac9809e830  __libc_start_main
    @           0x407d39  _start
    @              (nil)  (unknown)
Aborted (core dumped)
```

**Comment by Engineering-Course** [comment]
>`Check failed: matfp Error creating MAT file human/features/attentional/fc8_mask/labels/1270_1715217.png_blob_0.mat`

It seems that the filename of your mat is improper, which should not contain characters like ".png".

**Comment by lijiaqi** [comment]
@Engineering-Course  Thanks for your quick reply. With your advice, I have solved this problem. But I still have two questions:

1. It seems that the list of labels, e.g. written in ```val_id.txt```,  should not contains neither **the file suffix, .png** nor **path of label**. Just like this:
```
# in val_id.txt
1270_1715217
1271_474241
731_428532
...
```

But the list of images ```val.txt```  should be organized like this:
```
# in val.txt
images/1270_1715217.jpg
images/1271_474241.jpg
images/731_428532.jpg
```

Is this right?

2. I want to see the parsing results on my own dataset. Does it mean that I just need to collect the list of images in my dataset into ```test.txt```? Should I put something in ```test_id.txt```

**Comment by Engineering-Course** [comment]
Yes.
test_id.txt only contains the ids of images while test.txt contains the full paths.

**Comment by lijiaqi** [comment]
Now, both train and test processes work well in my experimental environment! Thanks ~
