### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by 22wei22** [Engineering-Course/LIP_SSL#8]
I can not download the model and lip dataset because  link address is bad.I can not login http://vision.sysu.edu.cn/

**Comment by Engineering-Course** [comment]
Check README file clearly, you can find the available links to download the model and dataset.

**Comment by 22wei22** [comment]
We have released our trained models with best performance here.if I click “here”  无法显示此网页
错误代码： HTTP ERROR -2146697211

**Comment by Engineering-Course** [comment]
Oh, this is a link to Google Drive.

**Comment by 22wei22** [comment]
不说英文了  谷歌是不是最近上不去   你提供的百度网盘里面有训练好的model么

**Comment by Engineering-Course** [comment]
我更新了README，上传model到了百度云

**Comment by 22wei22** [comment]
谢谢
